name: Initiate Release

on:
  push:
    branches:
      - main
    paths:
      - 'release.json'
  workflow_dispatch:
    inputs: 
      release:
        description: "Release type [alpha, beta, ca, ga]"
        required: true
      version:
        description: "Release Version"
        required: true

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Tag the deployment
        uses: daily-co/create-tag-action@v1.0
        with:
          app-name: 'my-application'
          environment: ${{github.event.inputs.release}}
          github-token: '${{ secrets.GITHUB_TOKEN }}'