name: Initiate Release

on:
  push:
    branches:
      - main
    paths:
      - 'release.json'
  workflow_dispatch:
    inputs: 
      release:
        description: "Release type [alpha, beta, ca, ga]"
        required: true
      version:
        description: "Release Version"
        required: true

jobs:
  tag-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    permissions: write-all

    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{github.event.inputs.version}}',
              sha: context.sha
            })
